[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:HASH_REDACTED"
  ]
[http.routers.api]
  rule = "Host(`dev.eli-beams.eu`) && Path(`/dashboard`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
